version: "3.9"

services:
  api:
    build: .
    container_name: credit-risk-api

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    environment:
      # IMPORTANT: match your MLflow setup (file-based tracking)
      - MLFLOW_TRACKING_URI=file:/app/mlruns

    restart: always
